# Generated by Django 3.2.5 on 2021-12-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='your_name',
            new_name='username',
        ),
    ]
