# Generated by Django 3.2.5 on 2021-12-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_your_name_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='repassword',
        ),
    ]
