# Generated by Django 3.2.5 on 2021-12-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211206_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Contact',
        ),
    ]
