# Generated by Django 3.2.5 on 2021-12-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_destination_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='passwordd',
            new_name='password',
        ),
    ]
